import type { Metadata } from "next";

import "./globals.css";
import ConfigProvider from "antd/es/config-provider";
import { componetsSettings, themeSettings } from "@/utils/theme-setting";
import ToastProvider from "@/providers/toast/toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: { icon: "/favicon.ico" },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ConfigProvider
        theme={{ token: themeSettings, components: componetsSettings }}
      >
        <ToastProvider />
        <body>{children}</body>
      </ConfigProvider>
    </html>
  );
}
